### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by Techout592** [TechHost-Development/Documentation#1]
### To-Do List 

- Documentation (Production)
  - [ ] Transition from old documentation based on free hosting to API details & endpoints.
  - [x] Update footer along with the links.
  - [x] Remove blog completely.

- Software 
  - [ ] Update software to the latest stable release.
